--
- hosts: centos
  become:
    true
  become_method:
    su
  become_user:
    ansible
  roles:
   - zabbix-agent-all

- hosts: ubuntu
  become:
    true
  become_method:
    sudo
  become_user:
    ansible
  roles:
   - zabbix-agent-all
